<a href="https://colab.research.google.com/github/Limm-jk/Neural-Networks-and-Deep-Learning/blob/main/Numpy_Vector.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

a = np.random.randn(5) # <- Rank 1 array

print(a)

[ 0.14580673  0.8548527   0.31304978 -0.17525618 -0.52541891]


In [2]:
print(a.shape)

(5,)


In [3]:
print(a.T)

[ 0.14580673  0.8548527   0.31304978 -0.17525618 -0.52541891]


In [4]:
print(np.dot(a,a.T))

1.1568126725781598


In [5]:
a = np.random.randn(5,1)
print(a)

[[ 0.78574235]
 [ 0.71874128]
 [ 0.6896282 ]
 [-0.28240552]
 [ 0.59882201]]


In [6]:
print(a.T)

[[ 0.78574235  0.71874128  0.6896282  -0.28240552  0.59882201]]


In [7]:
print(np.dot(a,a.T))

[[ 0.61739104  0.56474546  0.54187008 -0.22189798  0.47051981]
 [ 0.56474546  0.51658903  0.49566426 -0.20297651  0.4303981 ]
 [ 0.54187008  0.49566426  0.47558705 -0.19475481  0.41296455]
 [-0.22189798 -0.20297651 -0.19475481  0.07975288 -0.16911064]
 [ 0.47051981  0.4303981   0.41296455 -0.16911064  0.3585878 ]]


In [ ]:
# Rank 1 array를 사용하지마라.
# (5,1) (1,5)와 같은 확실한 column / row Vector의 구분을 가져서 사용해라

In [11]:
assert(a.shape == (5,1))